name: mine_sweeper
description: "A simple mine sweeper game made with Flutter and Rust."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  rust_lib_mine_sweeper:
    path: rust_builder
  flutter_rust_bridge: 2.8.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
